version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: tradetally-db-dev
    environment:
      POSTGRES_USER: ${DB_USER:-trader}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-trader_password}
      POSTGRES_DB: ${DB_NAME:-tradetally}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - trader-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-trader} -d ${DB_NAME:-tradetally}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Application (Frontend + Backend) - Built from local Dockerfile
  app:
    image: tradetally-app:dev
    container_name: tradetally-app-dev
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - path: .env
        required: true
    ports: #port 5173 open to web for auto loading changes on web
      - "5173:5173"
      - "3000:3000"
    volumes:
      # Backend - Hot-Mount for Development on nodemon
      # App Writen Data
      - ./backend/scripts:/app/backend/scripts
      - ./backend/uploads:/app/backend/uploads
      # ./backend/src/logs is coverd by /backend/src:app/backend/src
      # App Code Init and Hot-Running
      - ./backend/src:/app/backend/src
      - ./backend/migrations:/app/backend/migrations
      - ./backend/package.json:/app/backend/package.json
      - ./backend/package-lock.json:/app/backend/package-lock.json
      # Frontend
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./frontend/index.html:/app/frontend/index.html
      - ./frontend/package.json:/app/frontend/package.json
      - ./frontend/package-lock.json:/app/frontend/package-lock.json
      - ./frontend/postcss.config.js:/app/frontend/postcss.config.js
      - ./frontend/tailwind.config.js:/app/frontend/tailwind.config.js
      - ./frontend/vite.config.js:/app/frontend/vite.config.js
    networks:
      - trader-network-dev
    restart: unless-stopped

  # Optional: Adminer for database management
  adminer:
    image: adminer:latest
    container_name: tradetally-adminer-dev
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - trader-network-dev
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    restart: unless-stopped

networks:
  trader-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
    driver: local
